// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gagzbdicpbdrhigzibqo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdhZ3piZGljcGJkcmhpZ3ppYnFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwMDA0MDgsImV4cCI6MjA2NzU3NjQwOH0.uO9xBn2bK6M3iCwAuwb3bZoR3tTcE02xAJkOvuX9YWk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});